# Generated by Django 3.2.15 on 2022-09-14 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=100)),
                ('css', models.CharField(max_length=500)),
                ('categories', models.ManyToManyField(related_name='decos', to='Category.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variables', models.ManyToManyField(related_name='decos', to='Variable.Variable')),
            ],
        ),
    ]
