# Generated by Django 3.2.15 on 2022-09-15 10:50

import Deco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deco', '0002_alter_deco_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deco',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Deco.models.deco_image_file_path),
        ),
    ]
